language: java
notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - psantos@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
script:
  - ./gradlew assemble
after_success:
  - ./gradlew jacocoTestReport coveralls
